name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-n-test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    # - name: configure
    #   run: ./configure
    - name: export
      run: export
    - name: set
      run: set

    - name: make action (without error check)
      run: make action

    - name: run minishell
      run: ./minishell

    - name: execute testcases
      run: ./test.sh

    - name: make with -Wall -Wextra -Werror
      run: make