name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  check-environment:
    runs-on: macos-latest

    steps:
    - name: execute a one-line script
      run: echo "Checking environment"
    - name: export
      run: export
    - name: set
      run: set

# --------------------------------------------------------------

  build-n-test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    # - name: configure
    #   run: ./configure
    - name: make action (without error check)
      run: make action
    - name: run minishell
      run: ./minishell
    - name: make with -Wall -Wextra -Werror
      run: make
    - name: run minishell
      run: ./minishell
    
    - name: execute testcases
      run: echo "hello world" | ./minishell
    