name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    # - name: configure
    #   run: ./configure
    - name: find readline
      run: find /usr/local/Cellar/readline -name "libreadline.a"
    - name: find readline in opt
      run: find /usr/local/opt/readline -name "libreadline.a"
    - name: make
      run: make
    - name: run minishell
      run: ./minishell
    # - name: make check
    #   run: make check
    # - name: make distcheck
    #   run: make distcheck
