name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    # - name: configure
    #   run: ./configure
    - name: make action (without error check)
      run: make action

    - name: test minishell
      run: echo "hello world" | ./minishell
     
    - name: make all (with error check)
      run: make all